(function(){
  const sv=()=>document.documentElement.lang==='sv';
  const T=(a,b)=>sv()?a:b;
  function removeEmDashes(root=document.body){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.nodeValue&&/[—–]/.test(n.nodeValue))n.nodeValue=n.nodeValue.replace(/\s*[—–]\s*/g,' - ')});if(/[—–]/.test(document.title))document.title=document.title.replace(/\s*[—–]\s*/g,' - ')}
  function sourceCleanup(){document.querySelectorAll('.source-mini').forEach(x=>x.remove());document.querySelectorAll('.result .party-link').forEach(a=>{a.textContent=T('Officiell källa ↗','Official source ↗')})}
  function highlightImportant(){document.querySelectorAll('#screen-results .method-box').forEach(box=>{const h=box.querySelector('h3');if(h&&/^(Viktigt|Important)$/i.test(h.textContent.trim()))box.classList.add('important-callout')})}
  function moveResultActions(){const list=document.getElementById('resultsList');if(!list)return;const cards=[...list.querySelectorAll('.result')];if(cards.length<3)return;let mid=document.getElementById('midResultActions');if(!mid){mid=document.createElement('div');mid.id='midResultActions';mid.className='mid-result-actions';cards[2].after(mid)}const compare=document.getElementById('compareTop3Btn');const cont=document.getElementById('continueFromResultsBtn');if(compare&&compare.parentElement!==mid)mid.appendChild(compare);if(cont&&cont.parentElement!==mid)mid.appendChild(cont);if(compare)compare.classList.remove('hidden')}
  function fixMethodLabel(){const a=document.getElementById('methodologyLink');if(a)a.textContent=T('Metod & källor','Methodology & sources')}
  function comparisonAccents(){const rows=[...document.querySelectorAll('#compareRows .compare-row')];if(!rows.length||typeof vector!=='function'||typeof coords!=='function')return;const top=(typeof ranking==='function'?ranking():[]).filter(r=>state.acceptability[r.p]!=='veto').slice(0,3);const u=vector(),pc=coords();rows.forEach(row=>{const cells=[...row.querySelectorAll('.compare-cell')];cells.forEach(c=>c.classList.remove('match-close'));const topic=row.querySelector('.compare-topic strong')?.textContent||'';const modelDim=state.model?.dimensions?.find(x=>typeof dimName==='function'&&dimName(x.dimension)===topic);const d=modelDim?.dimension;if(!d||u[d]==null||cells.length<4)return;const distances=top.map(r=>Math.abs(u[d]-pc[r.p][d]));const min=Math.min(...distances);distances.forEach((dist,idx)=>{if(dist===min&&cells[idx+1])cells[idx+1].classList.add('match-close')})})}
  async function robustShare(){const summary=document.querySelector('.profile-summary h3')?.textContent?.trim()||T('Min politiska profil','My political profile');const traitList=[...document.querySelectorAll('.profile-summary .trait')].slice(0,5).map(x=>x.textContent.trim()).filter(Boolean);const text=[T('Min politiska profil','My political profile'),summary,traitList.join(' · '),'Find Your Politics - Sweden 2026'].filter(Boolean).join('\n');let status=document.querySelector('.share-status');if(!status){status=document.createElement('div');status.className='share-status';document.getElementById('shareProfileBtn')?.after(status)}try{if(navigator.share){await navigator.share({title:'Find Your Politics',text,url:location.href});status.textContent=T('Delningsmenyn öppnades.','Share menu opened.');return}}catch(e){if(e&&e.name==='AbortError')return}try{await navigator.clipboard.writeText(text+'\n'+location.href);status.textContent=T('Profilen kopierades. Klistra in den där du vill dela den.','Profile copied. Paste it wherever you want to share it.')}catch(e){window.prompt(T('Kopiera din profil:','Copy your profile:'),text+'\n'+location.href)}}
  function challengeFallback(){if(typeof vector!=='function'||typeof coords!=='function'||!state.bank)return;const ranked=ranking().filter(r=>state.acceptability[r.p]!=='veto').slice(0,3),pc=coords(),v=vector();const unused=state.bank.questions.filter(q=>!state.asked.includes(q.id));const qs=unused.map(q=>{const vals=ranked.map(r=>pc[r.p][q.primary_dimension]).filter(Number.isFinite);const spread=vals.length>1?Math.max(...vals)-Math.min(...vals):0;return{q,score:spread+(v[q.primary_dimension]==null?25:0)+(q.type==='discriminator'?12:0)}}).sort((a,b)=>b.score-a.score).slice(0,5).map(x=>x.q);if(!qs.length)return;state.comparisonQueue=qs.map(q=>q.id);state.viewingEarlyResults=true;const first=qs[0];state.comparisonQueue.shift();if(!state.asked.includes(first.id))state.asked.push(first.id);state.current=first;show('screen-quiz');renderQuestion(first)}
  document.addEventListener('click',e=>{const share=e.target.closest('#shareProfileBtn');if(share){e.preventDefault();e.stopImmediatePropagation();robustShare();return}const ch=e.target.closest('#challengeResultBtn');if(ch&&!ch.onclick){e.preventDefault();challengeFallback()}},true);
  function polish(){fixMethodLabel();sourceCleanup();highlightImportant();moveResultActions();comparisonAccents();removeEmDashes();const meta=document.querySelector('.meta');if(meta)meta.textContent='Sweden 2026 · V1.3.1'}
  let scheduled=false;const obs=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;polish()})});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('load',polish);polish();
})();